### ISSUE TITLE
Migrate to hooks [Proposal]

### ISSUE THREAD

**Issue by mrtnbroder** [frontarm/navi#101]
Hi there!

Wanted to say, love navi 💕 

I recently saw that styled-components migrated to hooks, and that using hooks improves dev-tools quality a lot. Read more about it here: https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987#7719

I think react-navi could benefit from this as well. I could spare some time to do this if you guys like the idea.

**Comment by jamesknelson** [comment]
Sure, I'd love any help with this!

Currently, it's already possible to use Navi without render components. The only components that are really necessary are `<Router>`, `<View>` and `<Link>`.

It might make sense to pull the control logic for `<Link>` out into a hook, and to have a hook that tells you whether a given URL is active. So there's that.

The `<Router>` component can't be a hook because it contains a context provider, and I think you wouldn't really want it to be a hook anyway.

The `<View>` component could *mostly* be rewritten as a hook, but there's one blocker -- it also contains a provider (which is used to tell any nested `<View>` to not render the same thing). Perhaps hooks could be used to clean up `<View>`'s internals, though.

If there any of these strike you as thing you'd like to give a try, or if you have any other ideas, then let's coordinate here with who does what.

**Comment by jamesknelson** [comment]
This could also be used to resolve https://github.com/frontarm/navi/issues/96

**Comment by jamesknelson** [comment]
Just published 0.13.0-alpha.0 which includes four new hooks:

- `useViewElement()` returns the element that would have been rendered by `<View />`. This makes animated transitions far simpler, as you can keep the element in state and it'll always render the same view as when it was first created.

- `useView()` is like `useViewElement()`, but returns an object with the raw view and head content, and a `connect()` function that you'll need to wrap them with. You can think of it like the render-prop version of `<View>`

- `useLinkProps(props)` accepts the same props as a `<Link>`, and returns an object with `href`, `onClick`, and any other props that you'd want to spread onto an `<a>`.

- `useActive(href)` returns `true` when the current route matches the specified href. You can use this along with `useLinkProps` to create your own custom styled links.

If you're still interested in this, I'd love to hear your thoughts!

**Comment by jamesknelson** [comment]
Closing this as I've just released 0.13.0 with `useViewElement()` et al. Feel free to re-open if you'd like to continue the discussion.
