### ISSUE TITLE
possible to change "routes" prop after-the-fact?

### ISSUE THREAD

**Issue by bryndyment** [frontarm/navi#122]
I have the following:

`<Router routes={mount(state.routes)}>`

Works great for my initial static routes.

I then update `state.routes` to include dynamic routes.

I've confirmed that `<Router>` is re-rendering its children after that state change.

I've also confirmed that `state.routes` contains the new routes.

However, my new route isn't functioning.  Before I attempt further debugging, I wanted to ask if such an approach should be supported.

(I am attempting to access the new route via Navi's `<Link>` component.)

Thx!

**Comment by jamesknelson** [comment]
That's an interesting application of `<Router>` -- I'd never thought of varying routes based on React state.

Currently it doesn't support it, as it only looks at the initial value of `routes`. Thinking about it, I don't think it really should work either, as it would be hard to get the interaction between React state and Navi route state to work correct.

Instead of doing this, what I'd suggest is to use a `map()` matcher to switch between routes based on some context, and pass a `context` prop to `<Router>` with all the required information.

Going to close this for now as I don't think any action needs to be taken on my side, but feel free to continue the conversation.
