### ISSUE TITLE
Example with CRA and hot module loading

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#127]
Can't seem to get HMR to work. Things that are routed to aren't being updated.

**Comment by lookfirst** [comment]
Looks like this is a WIP still:

https://github.com/facebook/create-react-app/issues/7227

**Comment by jamesknelson** [comment]
I haven't used hot reloading myself, but from the little I understand, hot module loading doesn't work so well with Navi because the routes are not components.

It may be possible to get it to work, but doing so I think would require changes to Navi itself, so that the matchers understand how to be reloaded and keep their state.

**Comment by lookfirst** [comment]
Ah, interesting. You are probably right with that. Something to consider for the future I guess.

**Comment by lookfirst** [comment]
FYI, I did get HMR + react-hot-loader working with parcel, but I don't fully trust it. If you're using latest react with hooks, you [have to do the config here](https://github.com/gaearon/react-hot-loader#react-hooks). It feels like there is just too many gotchas and I'm afraid it will screw things up during development. So we are back at just reloading the page, which is kind of lame. 2019 and we are still reloading the page to see changes. lol. I'm going to close this since it isn't really an issue with this library.

**Comment by jamesknelson** [comment]
Ok, thanks for the update.
