### ISSUE TITLE
query is not parsed properly

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#136]
I noticed this:

```ts
  /**
   * The values of any URL parameters matched from parameter segments in the
   * URLs, pathname, along with information from the URL's query string.
   */
  readonly params: { [name: string]: string }

  /**
   * An object containing the information from the URL's query string.
   */
  readonly query: { [name: string]: string }
```

What happens if I want to pass a query string of: `foo=bar&foo=ack`? 

https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys

When I tested this, all I saw was `foo=ack`.

**Comment by lookfirst** [comment]
I'm also not convinced that params should include query data. If they overlap unexpectedly, one will replace the other and that seems like failure of principle of least surprises.

**Comment by jamesknelson** [comment]
This isn't something I'd considered that anyone would want to do. I think the query will have the value of the last pair, but that'd be as much on accident as by design.

> I'm also not convinced that params should include query data. If they overlap unexpectedly, one will replace the other and that seems like failure of principle of least surprises.

I think you're probably right. Merging the two into a single `params` object is influenced by how Rails does things, but now you mention it, keeping them separate probably does make more sense. This would be a breaking change, but perhaps we should plan for that in the next big version bump. Would you be interested in putting together a PR?

**Comment by lookfirst** [comment]
Let's say you want to populate a `<select multiple>` from query string arguments, how would you do that?

PR at some point... super busy writing features right now. =(

**Comment by lookfirst** [comment]
Sure, a definite possibility and one of the ones suggested in SO. I'll close for now since there is no standard for this.
