### ISSUE TITLE
navi as react-native router

### ISSUE THREAD

**Issue by gut4** [frontarm/navi#154]
Is it possible to use navi as react-native router?

**Comment by jamesknelson** [comment]
It may be possible, but I've never tried it myself. If you do try this, you'd need to write your own integrations for e.g. deep linking and the Android back button.

**Comment by gut4** [comment]
Looks like it can work with ```Navi.createMemoryNavigation``` and ```useNavigation```
But there is a problem here:
https://github.com/frontarm/navi/blob/5a1762bfc8f8b2d30d810e1578f76aa41192d4f8/packages/react-navi/src/HashScroll.tsx#L23 
So for react-native we need to disable somehow hashScroll if there is no ```window```

**Comment by jamesknelson** [comment]
I see. Seems like there needs to be an option to pass a [HashScrollBehavior](https://github.com/frontarm/navi/blob/5a1762bfc8f8b2d30d810e1578f76aa41192d4f8/packages/react-navi/src/HashScroll.tsx#L3) of `none`.

If you're up to submitting a PR, this should be a pretty easy change. Otherwise I'll see if I can give it a shot this weekend or next weekend.
