### ISSUE TITLE
How to get navigation in getContent?

### ISSUE THREAD

**Issue by IzumiSy** [frontarm/navi#33]
Hi! I was impressed by your presentation in Nodefest in this year, and now am trying out react-navi right now to make my new app.

I just would like to know how to go to another path in `getContent`. The purpose of this is that I would like to change the rendering according to user login status like below. Can I get `navigation` from props or something? Thanks for your help.

```
export const RootComponent = Navi.createPage({
  title: 'index',
  getContent: async env => {
    const currentUser = await getCurrentUser();

    if (!currentUser) {
      // Wanna go to `/login` here
    }

    return component(currentUser)
  }
})

const component = (user: User) => {
  return (
    // ...
  )
}
```

**Comment by jamesknelson** [comment]
Hey, thanks for watching my talk! I'm glad you enjoyed it :-)

There's a way to do this that I'm still in the process of documenting. I should have some docs in the next week, but until then, here's how it works.

When you call `createSwitch`, you can pass `Page`, `Redirect` and `Switch` objects to `paths`. But you can also pass *functions* that return a `Page`, `Redirect` or `Switch`. If you *do* pass a function, the function receive a single argument called `env`, which is the same argument that `getContent` receives -- you can use this to get the requested path, which might be useful, e.g. for redirecting back after login.

Here's an example:

```js
Navi.createSwitch({
  paths: {
    '/': async env => {
      const currentUser = await getCurrentUser()

      if (!currentUser) {
        return Navi.createRedirect('/login?redirectTo='+env.pathname)
      }
      
      return Navi.createPage({
        title: 'index',
        getContent: () => component(currentUser),
      })
    }
  }
})
```

There's one more undocumented feature worth mentioning here: the `env` object has a `context` property that is passed through from your `Navigation` object. You can use this to pass the current authentication state through to your routes. You can also update it by calling `navigation.setContext` -- doing so recomputes the routes, so that users can be navigated away from a members-only page if they're logged out for some reason.

You can try this out with this [live example](https://frontarm.com/demoboard/?id=1229d493-ffaf-4133-b384-0f7dfec85af5), but here's the gist:

```js
Navi.createSwitch({
  paths: {
    '/': env =>
      !env.context.currentUser ? (
        Navi.createRedirect('/login?redirectTo='+env.pathname)
      ) : (
        Navi.createPage({
          title: 'index',
          getContent: () => component(currentUser),
        })
      )
  }
})

// ---

let currentUser = await getCurrentUser()
let navigation = Navi.createBrowserNavigation({
  pages,
  initialContext: {
    currentUser,
  }
})
```

I'll leave this issue open until I get this documented.

**Comment by IzumiSy** [comment]
Thank you very much for your contentful reply! Let me try that out.

**Comment by jamesknelson** [comment]
Just added a guide to the docs with this:

https://frontarm.com/navi/guides/authenticated-routes/
