### ISSUE TITLE
Proposal: support array of meta tags

### ISSUE THREAD

**Issue by vxna** [frontarm/navi#37]
For now, meta tags is an object and due to hardcoded [pattern](https://github.com/frontarm/navi/blob/master/packages/navi-scripts/lib/config.js#L145-L147), end result is always bound to `name=""` and `content=""` attributes. There is a variety of [other](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Other_types_of_metadata) attributes, so it seems a must to support this.

It's already possible with custom `navi.config.js`, but the main idea is to have more flexible defaults.

Users might like to write their meta this way:

```js
  '/': createPage({
      title: 'Navi',
      meta: [
        {
          name: 'description',
          content: 'navi-description'
        },
        {
          property: 'og:description',
          content: 'navi-og-description'
        }
      ]
  })
```

Some kind of draft implementation:
```js
  function generateMetaTags(attrs) {
    if (!Array.isArray(attrs)) return ''

    return attrs
      .map(
        attr =>
          `<meta ${Object.entries(attr)
            .map(([key, val]) => `${he.encode(key)}="${he.encode(val)}"`)
            .join(' ')}>`
      )
      .join('')
  }

  const title = `<title>${route.title || 'Untitled'}</title>`
  const meta = generateMetaTags(route.meta)
```

**Comment by jamesknelson** [comment]
Thanks for writing this up! I agree that the default behavior could be improved here.

Another issue is that ‘meta’ can serve as a way of storing metadata ther than the which gets rendered in the page head. For example, I use it to store the titles for the sidebar links on the docs website.

A further issue is that you may want to put things in the head other than meta tags.

It feels like perhaps there should be two things specified: “head” tags, and arbitrary data. Need to have a think about how to approach this.

**Comment by jamesknelson** [comment]
So one possibility that I’ve thought of is to merge ‘title’ and ‘meta’ into a single ‘head’ option, to which you can supply a JSX <head> — just like react-helmet.


    head:
      <>
        <title>My great page</title>
      </>


However, it would be possible to support a shorthand format where you can just pass a string if you only want to set a title.

The only catch is that this would make it hard to store info that shouldn’t be in the head or body - things like titles for nav bars. However, this could be resolved by adding an “info” option.

So pages would end up with:

- head
- content
- info

Would love to hear any thoughts on this.

**Comment by jamesknelson** [comment]
After thinking about this for a bit, I've decided to go with adding support for `head` and `getHead()` functions to Switches and Pages, while leaving the remaining `title`, `meta` and `content` as-is. Navi can just emit a warning if you provide both `title` and a `<head>` with a title inside it.

The idea would be that the `head` properties of each switch and page used for the current route will be merged into a single `<head>`, which can be easily rendered by navi-scripts -- just as with react-helmet. It should work without React being installed though, so we can't just use react-helmet, unfortunately.

This change should probably go along with two other to the `Route` objects:

- Instead of just including the page's `content`, it should contain an array of all `content` objects in switches and the final page.
- It should merge all the `meta` properties from switch objects together.

The result would be that a `Route` object has `head`, `meta` and `content` properties that contain all of the route's info, so it can easily be used to render the app.

Would be happy to accept a PR for this, otherwise will try and find some time for it in the next few weeks.

**Comment by jamesknelson** [comment]
This is now supported in Navi 0.11, by passing in `head` or `getHead()` to the `route()` matcher, or by using the `withHead()` matcher. Will be adding docs shortly.
