### ISSUE TITLE
Disable prefetch globally

### ISSUE THREAD

**Issue by jdiamond** [frontarm/navi#55]
Is it possible to disable prefetching everywhere without putting `prefetch={false}` on all my links?

**Comment by jamesknelson** [comment]
While it's a bit of a hack, you should be able to disable it by importing `Link` and setting the default prop:

```js
import { Link } from 'react-navi'

Link.defaultProps.prefetch = null
```

I'm not even sure prefetch should be enabled globally, though. I like it because it can provide a warning if the URL is a 404, but might be best disabled, or at least improved so that the prefetch only happens when the link is visible on screen.

Any thoughts on this?

**Comment by jdiamond** [comment]
I don't have any experience with prefetching yet but I think I agree that I would probably never want to enable it by default for all links.

I'm actually trying to disable it, though, because it seems like it's already enabled by default.

While working on a page, I'm trying to find the network request for just the page I'm working on so I can look at the headers and whatever, but it's mixed up with all the other requests caused by links being prefetched and running all the withData, getData, etc, functions.

I started setting `prefetch={false}` everywhere to get it to stop, but I ended up making a simple wrapper Link component around react-navi's Link and changed all my components to use the wrapper.

I thought seeing the warnings about invalid links was cool but maybe that feature can be done in a way that doesn't require prefetching?

To be honest, I'm not sure when I would ever want to do prefetching so I would vote to disable it by default, but let me opt-in on a link-by-link basis.

One thing that worried me was the "burstiness" of the prefetching. It seems like all of the getData, etc, requests were happening at once and I was wondering if I could delay or throttle them.

**Comment by jamesknelson** [comment]
Unfortunately the invalid link warnings would be pretty hard to implement without prefetch. Because of the `withContext() and `map()` matchers, the matched route can depend on data fetched from elsewhere, and `route()` uses `withContext()` internally so I couldn't just ignore routes with context. Given that it's also possible to create custom matchers, invalid link warnings are always going to need prefetch.

I think I'm going to go ahead and disable prefetch-by-default though, as you suggest. It's always possible to create a wrapper component that enables it -- basically the opposite of what you've done.

**Comment by jamesknelson** [comment]
I've set prefetch={false} as the default in master and will release in the next minor version.

**Comment by jdiamond** [comment]
Cool, thanks!

**Comment by JacksonGariety** [comment]
Can we still do this? The new `hover` behavior is sub-optimal because I add/remove a loading spinner in `getView`, and so it appears and goes away when you move the mouse around. A little bit jarring.
