### ISSUE TITLE
Provide a way for Link children to access 'active'.

### ISSUE THREAD

**Issue by fahrradflucht** [frontarm/navi#96]
## Problem
I want to render different children into a `<Link />` based on whether it is active or not. I didn't find a way to access the information though without replicating the logic inside of the `<Link />` component itself.

## Solution
Provide a way for link children to access the `active` state. For example by allowing to pass a render prop to `<Link />` which gets this information.

**Comment by jamesknelson** [comment]
The `<Link>` component already accepts a `render` prop, it just needs to be documented. I'll see if I can do that today.

**Comment by jamesknelson** [comment]
Instead of documenting the old render prop way, I've just published two new hooks with 0.13.0-alpha.0:

- `useLinkProps(props)` accepts the same props as a `<Link>`, and returns an object with `href`, `onClick`, and any other props that you'd want to spread onto an `<a>`.

- `useActive(href)` returns `true` when the current route matches the specified href. You can use this along with `useLinkProps` to create your own custom styled links.

The `<Link>` component now uses these internally, so you can basically create your own custom `<Link>` component using these in two lines.

0.13.0-alpha.0 is basically ready to go, but is just missing documentation. If you're still looking for a solution, it might be worth trying out :-)
